
package com.example.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RouterSenderService", targetNamespace = "http://sender.server.dobrodey.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RouterSenderService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/notifyUserRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/notifyUserResponse")
    public void notifyUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns com.example.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/getAdminsRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/getAdminsResponse")
    public ListOfString getAdmins();

    /**
     * 
     * @return
     *     returns com.example.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/getLecturersRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/getLecturersResponse")
    public ListOfString getLecturers();

    /**
     * 
     * @return
     *     returns com.example.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/getThreeDaysNotTrackingUsersRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/getThreeDaysNotTrackingUsersResponse")
    public ListOfString getThreeDaysNotTrackingUsers();

    /**
     * 
     * @return
     *     returns com.example.generate.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sender.server.dobrodey.ru/RouterSenderService/getOneDaysNotTrackingUsersRequest", output = "http://sender.server.dobrodey.ru/RouterSenderService/getOneDaysNotTrackingUsersResponse")
    public ListOfString getOneDaysNotTrackingUsers();

}
